### PR TITLE
Fail if there are jobs registered without any arguments.

### LINKED ISSUE #873: Mirage_logs/Logs doesn't work at top-level
Suppose we have the following ```config.ml```:
```ocaml
open Mirage

let main = foreign "Unikernel" job

let () =
  let packages = [] in
  register "test" ~packages [main]
```
and the following ```unikernel.ml```:
```ocaml
let start =
  Logs.info (fun f -> f "Hello world !");
  Lwt.return_unit
```
If we execute it, the hello world is not displayed. This behaviour doesn't happen if ```start``` become a function as ```Mirage_logs``` will be initialized before the call to ```Logs.info```.

I wonder if something can be done in [mirage/functoria](https://github.com/mirage/functoria). Maybe there is a way to enforce or warn if we don't have a functor/function or something.

### PR DESCRIPTION
**Pull request by hannesm**
This ensures that toplevel expressions in the unikernels are properly evaluated.

Fixes #873 #1426

//cc @reynir

To test with: https://github.com/mirage/mirage-skeleton/pull/359

### CODE REVIEW

File: lib/mirage/mirage.ml [hunk 1]
```diff
@@ -485,6 +485,12 @@ let ( ++ ) acc x =
 
 let register ?(argv = default_argv) ?tracing ?(reporter = default_reporter ())
     ?keys:extra_keys ?packages ?src name jobs =
+  if List.exists Functoria.Impl.app_has_no_arguments jobs then
+    invalid_arg "Your configuration includes a job without arguments. \
+                 Please add a dependency in your config.ml: use \
+                 `let main = Mirage.main \"Unikernel.hello\" (noop @-> job) \
```
Comment (palainp) [inline lib/mirage/mirage.ml:491]: Regarding the example later, it should be `let main = Mirage.main \"Unikernel.hello\" (job @-> job) \`, no?

File: test/mirage/job-no-device/configure.t [hunk 2]
```diff
@@ -0,0 +1,6 @@
+  $ export MIRAGE_DEFAULT_TARGET=unix
+
+Configure
+  $ ./config.exe configure
+  Fatal error: exception Invalid_argument("Your configuration includes a job without arguments. Please add a dependency in your config.ml: use `let main = Mirage.main \"Unikernel.hello\" (noop @-> job) register \"hello\" [ main $ noop ]` instead of `.. job .. [ main ]`.")
```
Comment (palainp) [inline test/mirage/job-no-device/configure.t:5]: Same here, `(job @-> job)`

File: lib/functoria/impl.ml [hunk 3]
```diff
@@ -42,6 +42,17 @@ and 'a device = ('a, abstract) Device.t
...
 
+let app_has_no_arguments = function
+  | App { args ; _ } ->
+    (match args with
+     | Cons _ -> false
+     | _ -> true)
+  | Dev { args ; _ } ->
+    (match args with
+     | Cons _ -> false
+     | _ -> true)
```
Comment (palainp) [inline lib/functoria/impl.ml:53]: Here there is no distinction between `App` and `Dev`. So we can simplify things by deleting lines 46 to 49. But I'm not sure an unikernel using a device without arguments won't also fail (or is supposed to?). I surely have to look deeper into it :)

**Review by palainp — COMMENTED** [review]
Thanks @hannesm that sounds great to me! I'll try to look deeper regarding my first comment but the PR might get merged before I'm done :)

File: lib/mirage/mirage.ml (hunk 1 above)
Comment (hannesm) [reply lib/mirage/mirage.ml]: indeed, thanks for spotting this, fixed in 28e80385

File: lib/functoria/impl.ml (hunk 3 above)
Comment (hannesm) [reply lib/functoria/impl.ml:53]: I tried and failed due to GADT and the OCaml compiler complaining about types escaping its scope. But feel free to experiment with that and find a good solution :)

Comment (reynir) [inline lib/functoria/impl.ml:53]:
```suggestion
let app_has_no_arguments = function
  | App { args = Cons _ ; _ } | Dev { args = Cons _ ; _ } -> false
  | App _ | Dev _ -> true

```

Comment (hannesm) [reply lib/functoria/impl.ml]: thanks, done in 85886a1a

Comment (hannesm) [reply lib/functoria/impl.ml]: see 85886a1a (as proposed by @reynir)

File: lib/functoria/impl.ml [hunk 4]
```diff
@@ -43,15 +43,9 @@ and 'a device = ('a, abstract) Device.t
...
-     | Cons _ -> false
-     | _ -> true)
-  | Dev { args ; _ } ->
-    (match args with
-     | Cons _ -> false
-     | _ -> true)
-  | If _ -> false
+  | App { args = Cons _ ; _ }
+  | Dev { args = Cons _ ; _ } -> false
+  | _ -> false
```
Comment (palainp) [inline lib/functoria/impl.ml:48]: Should be true :)

Comment (hannesm) [reply lib/functoria/impl.ml]: true that is, I adjusted this in [b9b9ddb](https://github.com/mirage/mirage/pull/1428/commits/b9b9ddbb80b00d5762e82d8b62e339577d1667c0)

**Comment by hannesm** [comment]
Requires https://github.com/mirage/mirage/pull/1428
